### ISSUE TITLE
ice-mods explanation

### ISSUE THREAD

**Issue by psprint** [DundarGoc/zplugin_readme#2]
Hello,
I saw that one user didn't know what ice-mods are (in the issue). Could the explanation be restored somewhere, the one with the ice-melting, etc.?

I like the restructure.

**Comment by psprint** [comment]
I've noticed that the explanation was always only in the introduction, so I've added it to the [Ice Modifiers](https://github.com/zdharma/zplugin#ice-modifiers) section.

**Comment by DundarGoc** [comment]
Ah, completely missed that you had made an issue. I'll keep an eye out for it from now on. I read the edit you did to Ice modifiers, I think it looks good.

**Comment by DundarGoc** [comment]
@psprint I completely missed that you had made an issue. I've enabled notifications so I'll be able to see it if you make a new issue from now on. I read the edit you did to Ice modifiers, I think it looks good. I'm glad to hear you like it.
